version: 2

models:
  - name: int_page_views
    description: A model to show total pageviews by product

  - name: int_purchases
    description: A model to show total purchases by product

  - name: int_session_events_agg
    description: A model to show the aggregated number of events by user_guid and session_guid


