version: 2

models:
  - name: stg_postgres__addresses
    description: Address information for each order
    columns:
      - name: address_guid
        tests:
          - not_null
          - unique

  - name: stg_postgres__users
    description: User information
    columns:
      - name: user_guid
        tests:
          - not_null
          - unique

  - name: stg_postgres__promos
    description: Promo code information
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique

  - name: stg_postgres__products
    description: Products and inventory information
    columns:
      - name: product_guid
        tests:
          - not_null
          - unique

  - name: stg_postgres__orders
    description: Order information
    columns:
      - name: order_guid
        tests:
          - not_null
          - unique

  - name: stg_postgres__order_items
    description: Order items information including product and quantity
    columns:
      - name: product_guid
        tests:
          - not_null
          - unique

  - name: stg_postgres__events
    description: Event information
    columns:
      - name: event_guid
        tests:
          - not_null
          - unique
      - name: session_guid
        tests:
          - not_null
          - unique